"""Add crypto table

Revision ID: cd59b9cbc003
Revises: 
Create Date: 2025-03-30 21:13:34.099728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd59b9cbc003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('hashing_algorithm', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coingecko_id')
    )
    op.create_index(op.f('ix_crypto_currency_id'), 'crypto_currency', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_currency_id'), table_name='crypto_currency')
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
