"""Add indexes

Revision ID: 4b29622204a8
Revises: fa44df4ee2d4
Create Date: 2025-03-31 20:41:46.984866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b29622204a8'
down_revision: Union[str, None] = 'fa44df4ee2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crypto_currency_coingecko_id_key', 'crypto_currency', type_='unique')
    op.create_index('idx_crypto_currency_categories_gin', 'crypto_currency', ['categories'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_crypto_currency_coingecko_id'), 'crypto_currency', ['coingecko_id'], unique=True)
    op.create_index(op.f('ix_crypto_currency_hashing_algorithm'), 'crypto_currency', ['hashing_algorithm'], unique=False)
    op.create_index(op.f('ix_crypto_currency_name'), 'crypto_currency', ['name'], unique=False)
    op.create_index(op.f('ix_crypto_currency_symbol'), 'crypto_currency', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_currency_symbol'), table_name='crypto_currency')
    op.drop_index(op.f('ix_crypto_currency_name'), table_name='crypto_currency')
    op.drop_index(op.f('ix_crypto_currency_hashing_algorithm'), table_name='crypto_currency')
    op.drop_index(op.f('ix_crypto_currency_coingecko_id'), table_name='crypto_currency')
    op.drop_index('idx_crypto_currency_categories_gin', table_name='crypto_currency', postgresql_using='gin')
    op.create_unique_constraint('crypto_currency_coingecko_id_key', 'crypto_currency', ['coingecko_id'])
    # ### end Alembic commands ###
